parameters:
  - name: deploymentType
    type: string
  - name: environmentName
    type: string
  - name: subscriptionName
    type: string

stages:
  - stage: Provision_${{ parameters.environmentName }}
    dependsOn: DeploymentPreparation
    displayName: "Deploy to ${{ parameters.environmentName }} (${{ variables['Build.SourceBranch'] }}) Stage"
    jobs:
        - template: ../jobs/provision-sql-server.yml
          parameters:
            deploymentType: ${{ parameters.deploymentType }}
            environmentName: ${{ parameters.environmentName }}
            subscriptionName: ${{ parameters.subscriptionName }}
            runAfter: []