trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pipeline
      - infra
      - src
    exclude:
      - README.md
      - .gitignore

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: deploymentType
    displayName: Deployment Type
    type: string
    values:
    - All
    - Code
    - Provisioning
    default: All
  - name: connectionString
    displayName: "Connection String"
    type: string
  - name: subscriptionName
    type: string
    default: AshleyGibsonSubscription

stages:
  - template: stages/build-and-test.yml
    parameters:
      deploymentType: ${{ parameters.deploymentType }}
  
  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual') }}:
    - template: pipeline/stages/deployment-preparation.yml@AshTemplates
      parameters:
         runAfter: 
          - Build_And_Test

#######################################################################
# Provision to Production
#######################################################################
  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual') }}:
    - template: stages/provision-environment.yml
      parameters:
        deploymentType: ${{ parameters.deploymentType }}
        environmentName: prod
        stage: Prod
        subscriptionName: ${{ variables.subscriptionName }}
        dockerImageRepository: $(dockerImageRepository)
        dockerImageTag: $(dockerImageTag)
        databaseSku:
          sku: Basic
          tier: Basic

#######################################################################
# Tag the Build
#######################################################################
  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual') }}:
    - template: pipeline/stages/tag-build.yml@AshTemplates