trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pipeline
      - infra
      - src
    exclude:
      - README.md
      - .gitignore

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: deploymentType
    displayName: Deployment Type
    type: string
    values:
    - All
    - Code
    - Provisioning
    default: All
  - name: subscriptionName
    type: string
    default: AshleyGibsonSubscription

stages:  
  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual') }}:
    - template: stages/deployment-preparation.yml

#######################################################################
# Provision to Production
#######################################################################
  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual') }}:
    - template: stages/provision-environment.yml
      parameters:
        deploymentType: ${{ parameters.deploymentType }}
        environmentName: prod
        subscriptionName: ${{ variables.subscriptionName }}

#######################################################################
# Tag the Build
#######################################################################
  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual') }}:
    - template: pipeline/stages/tag-build.yml@AshTemplates